default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: todos_app_api_rewrite_development

test:
  <<: *default
  database: todos_app_api_rewrite_test

production:
  <<: *default
  database: todos_app_api_rewrite_production
  username: todos_app_api_rewrite
  password: <%= ENV['TODOS_APP_API_REWRITE_DATABASE_PASSWORD'] %>
